import { BasketIcon } from "@sanity/icons";
import { defineArrayMember, defineField, defineType } from "sanity";

export const orderType = defineType({
  name: "order",
  title: "Order",
  type: "document",
  icon: BasketIcon,
  fields: [
    defineField({
      name: "orderNumber",
      title: "Order Number",
      type: "string",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "clerkUserId",
      title: "Store User ID",
      type: "string",
    }),
    defineField({
      name: "customerName",
      title: "Customer Name",
      type: "string",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "phoneNumber",
      title: "Phone Number",
      type: "string",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "alternativePhone",
      title: "Alternative Phone Number",
      type: "string",
    }),
    defineField({
      name: "email",
      title: "Customer Email",
      type: "string",
      validation: (Rule) => Rule.required().email(),
    }),
    defineField({
      name: "officeCode",
      title: "Office Code",
      type: "string",
    }),
    defineField({
      name: "district",
      title: "District",
      type: "string",
      validation: (Rule) => Rule.required(),
      options: {
        list: [
          { title: "Dhaka City", value: "dhaka_city" },
          { title: "Chittagong", value: "chittagong" },
          { title: "Sylhet", value: "sylhet" },
          { title: "Rajshahi", value: "rajshahi" },
          { title: "Khulna", value: "khulna" },
          { title: "Barisal", value: "barisal" },
          { title: "Rangpur", value: "rangpur" },
          { title: "Mymensingh", value: "mymensingh" },
        ],
      },
    }),
    defineField({
      name: "thana",
      title: "Thana/Upazila",
      type: "string",
      validation: (Rule) => Rule.required(),
      options: {
        list: [
          { title: "Adabor", value: "adabor" },
          { title: "Airport", value: "airport" },
          { title: "Ati Bazar (Keraniganj)", value: "ati_bazar_keraniganj" },
          { title: "Azompur", value: "azompur" },
          { title: "Badda", value: "badda" },
          { title: "Banani", value: "banani" },
          { title: "Bangshal", value: "bangshal" },
          { title: "Bashundhara R/A", value: "bashundhara_r_a" },
          { title: "Bhashantek", value: "bhashantek" },
          { title: "Cantonment", value: "cantonment" },
          { title: "Chalkbazar", value: "chalkbazar" },
          { title: "Dakshin khan", value: "dakshin_khan" },
          { title: "Darus Salam", value: "darus_salam" },
          { title: "Demra", value: "demra" },
          { title: "Dhanmondi", value: "dhanmondi" },
          { title: "Gandaria", value: "gandaria" },
          { title: "Gulistan", value: "gulistan" },
          { title: "Gulshan", value: "gulshan" },
          { title: "Hatirjheel", value: "hatirjheel" },
          { title: "Hazaribag", value: "hazaribag" },
          { title: "Jattrabari", value: "jattrabari" },
          { title: "Kadamtali", value: "kadamtali" },
          { title: "Kafrul", value: "kafrul" },
          { title: "Kalabagan", value: "kalabagan" },
          { title: "Kamrangirchar", value: "kamrangirchar" },
          { title: "Khilgaon", value: "khilgaon" },
          { title: "Khilkhet", value: "khilkhet" },
          { title: "Kotwali", value: "kotwali" },
          { title: "Lalbagh", value: "lalbagh" },
          { title: "Mirpur", value: "mirpur" },
          { title: "Mohammadpur", value: "mohammadpur" },
          { title: "Motijheel", value: "motijheel" },
          { title: "Mugda", value: "mugda" },
          { title: "New Market", value: "new_market" },
          { title: "Pallabi", value: "pallabi" },
          { title: "Paltan", value: "paltan" },
          { title: "Panthapath", value: "panthapath" },
          { title: "Purbachal", value: "purbachal" },
          { title: "Ramna", value: "ramna" },
          { title: "Rampura", value: "rampura" },
          { title: "Rupnagar", value: "rupnagar" },
          { title: "Sabujbag", value: "sabujbag" },
          { title: "Shah Ali", value: "shah_ali" },
          { title: "Shah Ali Market", value: "shah_ali_market" },
          { title: "Shahbag", value: "shahbag" },
          { title: "Shahjahanpur", value: "shahjahanpur" },
          { title: "Sher-e-Bangla Nagar", value: "sher_e_bangla_nagar" },
          { title: "Shyampur", value: "shyampur" },
          { title: "Sutrapur", value: "sutrapur" },
          { title: "Tejgaon", value: "tejgaon" },
          { title: "Tejgaon Industrial Area", value: "tejgaon_industrial_area" },
          { title: "Turag", value: "turag" },
          { title: "Uttara", value: "uttara" },
          { title: "Uttarkhan", value: "uttarkhan" },
          { title: "Vasantek", value: "vasantek" },
          { title: "Vatara", value: "vatara" },
          { title: "Wari", value: "wari" },
          { title: "Zone Not Clear", value: "zone_not_clear" },
        ],
      },
    }),
    defineField({
      name: "shippingMethod",
      title: "Shipping Method",
      type: "string",
      validation: (Rule) => Rule.required(),
      options: {
        list: [
          { title: "Inside Dhaka (Tk 70.00)", value: "inside_dhaka" },
          { title: "Inside Chittagong (Tk 70.00)", value: "inside_chittagong" },
          { title: "Outside above cities (Tk 130.00)", value: "outside_cities" },
        ],
      },
    }),
    defineField({
      name: "shippingCost",
      title: "Shipping Cost",
      type: "number",
      validation: (Rule) => Rule.required().min(0),
    }),
    defineField({
      name: "paymentMethod",
      title: "Payment Method",
      type: "string",
      validation: (Rule) => Rule.required(),
      options: {
        list: [
          { title: "Cash on Delivery", value: "cod" },
          { title: "Mobile Banking", value: "mobile_banking" },
          { title: "Bank Transfer", value: "bank_transfer" },
        ],
      },
      initialValue: "cod",
    }),
    defineField({
      name: "products",
      title: "Products",
      type: "array",
      of: [
        defineArrayMember({
          type: "object",
          fields: [
            defineField({
              name: "product",
              title: "Product Bought",
              type: "reference",
              to: [{ type: "product" }],
            }),
            defineField({
              name: "quantity",
              title: "Quantity Purchased",
              type: "number",
            }),
            defineField({
              name: "priceAtTime",
              title: "Price at Time of Purchase",
              type: "number",
              validation: (Rule) => Rule.required().min(0),
            }),
          ],
          preview: {
            select: {
              product: "product.name",
              quantity: "quantity",
              image: "product.images",
              price: "priceAtTime",
            },
            prepare(select) {
              return {
                title: `${select.product} x ${select.quantity}`,
                subtitle: `Tk ${(select.price * select.quantity).toFixed(2)}`,
                media: select.image?.[0],
              };
            },
          },
        }),
      ],
    }),
    defineField({
      name: "subtotal",
      title: "Subtotal",
      type: "number",
      validation: (Rule) => Rule.required().min(0),
    }),
    defineField({
      name: "discountAmount",
      title: "Discount Amount",
      type: "number",
      validation: (Rule) => Rule.min(0),
      initialValue: 0,
    }),
    defineField({
      name: "discountCode",
      title: "Discount Code Used",
      type: "string",
    }),
    defineField({
      name: "discountCodeId",
      title: "Discount Code Reference",
      type: "reference",
      to: [{ type: "discountCode" }],
      description: "Reference to the discount code document",
    }),
    defineField({
      name: "totalPrice",
      title: "Total Price",
      type: "number",
      validation: (Rule) => Rule.required().min(0),
    }),
    defineField({
      name: "currency",
      title: "Currency",
      type: "string",
      validation: (Rule) => Rule.required(),
      initialValue: "BDT",
    }),
    defineField({
      name: "address",
      title: "Shipping Address",
      type: "object",
      fields: [
        defineField({ 
          name: "fullAddress", 
          title: "Full Address", 
          type: "text",
          validation: (Rule) => Rule.required(),
        }),
        defineField({ 
          name: "district", 
          title: "District", 
          type: "string",
          validation: (Rule) => Rule.required(),
        }),
        defineField({ 
          name: "thana", 
          title: "Thana/Upazila", 
          type: "string",
          validation: (Rule) => Rule.required(),
        }),
        defineField({ 
          name: "name", 
          title: "Recipient Name", 
          type: "string",
          validation: (Rule) => Rule.required(),
        }),
      ],
    }),
    defineField({
      name: "status",
      title: "Order Status",
      type: "string",
      options: {
        list: [
          { title: "Pending", value: "pending" },
          { title: "Processing", value: "processing" },
          { title: "Out for Delivery", value: "out_for_delivery" },
          { title: "Delivered", value: "delivered" },
          { title: "Cancelled", value: "cancelled" },
        ],
      },
      initialValue: "pending",
    }),
    defineField({
      name: "orderDate",
      title: "Order Date",
      type: "datetime",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "notes",
      title: "Order Notes",
      type: "text",
    }),
  ],
  preview: {
    select: {
      name: "customerName",
      amount: "totalPrice",
      currency: "currency",
      orderId: "orderNumber",
      email: "email",
      status: "status",
      paymentMethod: "paymentMethod",
    },
    prepare(select) {
      const orderIdSnippet = `${select.orderId?.slice(0, 5)}...${select.orderId?.slice(-5)}`;
      return {
        title: `${select.name} (${orderIdSnippet})`,
        subtitle: `${select.amount} ${select.currency} • ${select.paymentMethod?.toUpperCase()} • ${select.status}`,
        media: BasketIcon,
      };
    },
  },
});
